backend/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import (
    customer_login,
    delivery_person_login,
    restaurant_login,
    account_logout,
    send_otp_code,
    AccountDetails,
)

app_name = "accounts"

urlpatterns = [
    path("send-otp/", send_otp_code, name="send_otp"),
    path("login/", customer_login, name="customer_login"),
    path("login/delivery-person/", delivery_person_login, name="delivery_person_login"),
    path("login/restaurant/", restaurant_login, name="restaurant_login"),
    path(
          "logout/restaurant/",
          auth_views.LogoutView.as_view(
               template_name="accounts/logout.html"
          ),
          name="restaurant_logout"
    ),
    path("logout/", account_logout, name="logout"),
    path("details/", AccountDetails.as_view(), name="details"),
]

backend/api/urls.py
from django.urls import path

from api.views import APIRoot, Search


app_name = "api"

urlpatterns = [
    path("", APIRoot.as_view(), name="api-root"),
    path("search/", Search.as_view(), name="search")
]

backend/foodie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurants.urls")),
    path("api/", include("api.urls")),
    path("accounts/", include("accounts.urls")),
    path("foods/", include("foods.urls")),
    path("customers/", include("customers.urls")),
    path("cart/", include("cart.urls")),
    path("reviews/", include("reviews.urls")),
    path("orders/", include("orders.urls")),
    path("favourites/", include("favourites.urls")),
    path("delivery-person/", include("delivery_person.urls", namespace="delivery_person")),
]

# Admin Site Configurations

admin.site.site_header = "Foodie Administration"
admin.site.index_title = "Models Administration"
admin.site.site_title = "Foodie Admin"

backend/foods/urls.py
from django.urls import path

from foods.views import (
    FoodList, 
    FoodDetails, 
    FoodTemplateList, 
    FoodTemplateDetailsView
)

app_name = "foods"

urlpatterns = [
    path("", FoodList.as_view(), name="food_list"),
    path("<int:pk>/", FoodDetails.as_view(), name="food_details"),
    path("templates/", FoodTemplateList.as_view(), name="food_template_list"),
    path("templates/<int:pk>/", FoodTemplateDetailsView.as_view(), name="food_template_details"),
]

backend/restaurants/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from restaurants.views import (
    restaurant_dashboard,
    RestaurantDetails,
    RestaurantList,
    FoodCreateView,
    FoodDeleteView,
    FoodDetailView,
    FoodListView,
    FoodUpdateView,
    account_settings,
    change_password,
    get_location,
    update_location,
)


app_name = "restaurants"

urlpatterns = [
    # APIs for mobile app
    path("restaurants/", RestaurantList.as_view(), name="restaurant_list"),
    path("restaurants/<int:pk>/", RestaurantDetails.as_view(), name="restaurant_details"),

    # URLs for restaurant dashboard
    path("", restaurant_dashboard, name="restaurant_home"),
    path("restaurant/foods/", FoodListView.as_view(), name="food_list"),
    path("restaurant/foods/new/", FoodCreateView.as_view(), name="food_create"),
    path("restaurant/foods/new/<int:template_id>/", FoodCreateView.as_view(),
         name="food_create_from_template"),
    path("restaurant/foods/<int:pk>/", FoodDetailView.as_view(), name="food_detail"),
    path("restaurant/foods/edit/<int:pk>/", FoodUpdateView.as_view(), name="food_update"),
    path("restaurant/foods/delete/<int:pk>/", FoodDeleteView.as_view(), name="food_delete"),
    path("restaurant/account/settings/profile/", account_settings, name="account_settings"),
    path("restaurant/account/settings/password/", change_password, name="change_password"),
    path("restaurant/location/", get_location, name="get_location"),
    path("restaurant/location/update/", update_location, name="update_location"),
]

backend/foods/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models import Avg, Count
from decimal import Decimal

from taggit.managers import TaggableManager
from cloudinary.models import CloudinaryField

from restaurants.models import Restaurant
from reviews.models import Review
from favourites.models import Favourite
from api.custom_managers import AvailabilityManager
from customers.models import Customer


class Food(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal("0.01"))])
    is_available = models.BooleanField(default=True)
    image = CloudinaryField("image", blank=True, folder="media/foods/")
    discount_percent = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)
        ]
    )
    restaurant = models.ForeignKey(
        Restaurant,
        related_name="foods",
        on_delete=models.CASCADE
    )
    is_veg = models.BooleanField(default=False)
    reviews = GenericRelation(
        Review,
        related_query_name="food",
        content_type_field="content_type",
        object_id_field="object_id",
    )
    favourites = GenericRelation(
        Favourite,
        related_query_name="food",
        content_type_field="content_type",
        object_id_field="object_id",
    )
    created = models.TimeField(auto_now_add=True)
    updated = models.TimeField(auto_now=True)

    # Managers
    objects = models.Manager()
    available = AvailabilityManager()
    tags = TaggableManager()

    class Meta:
        ordering = ("-is_available", "-discount_percent", "name",)

    @property
    def selling_price(self):
        return self.price - (self.price * self.discount_percent/100)

    @property
    def average_ratings(self):
        avg_ratings = self.reviews.aggregate(Avg("ratings")).get("ratings__avg", 0)
        if avg_ratings == None: avg_ratings = 0
        return avg_ratings

    @property
    def ratings_count(self):
        ratings_cnt = self.reviews.aggregate(Count("ratings")).get("ratings__count", 0)
        if ratings_cnt == None: ratings_cnt = 0
        return ratings_cnt

    def customer_favourite_status(self, id):
        try:
            customer = Customer.objects.get(id=id)
            item = self.favourites.filter(customer=customer)
            if item:
                return True
            return False
        except ObjectDoesNotExist:
            return False

    @property
    def can_be_ordered(self):
        return self.is_available and self.restaurant.is_available and self.restaurant.open_status

    def __str__(self):
        return f"Food: {self.name} for restaurant {self.restaurant.user.full_name}"


class FoodTemplate(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal("0.01"))])
    is_available = models.BooleanField(default=True)
    image = CloudinaryField("image", blank=True, folder="media/templates/")
    is_veg = models.BooleanField(default=False)
    usage = models.IntegerField(default=0)
    created = models.TimeField(auto_now_add=True)
    updated = models.TimeField(auto_now=True)

    # Managers
    objects = models.Manager()
    available = AvailabilityManager()
    tags = TaggableManager()

    class Meta:
        ordering = ("-is_available", "-usage", "name",)

    def __str__(self):
        return f"FoodTemplate: {self.name}"

backend/restaurants/models.py
import datetime
import pytz

from django.contrib.contenttypes.fields import GenericRelation
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import models
from django.db.models import Avg, Count
from django.db.models.signals import post_delete
from django.dispatch import receiver

from taggit.managers import TaggableManager
from cloudinary.models import CloudinaryField
from django_better_admin_arrayfield.models.fields import ArrayField

from accounts.models import User
from api.custom_managers import AvailabilityManager
from customers.models import Customer
from favourites.models import Favourite
from reviews.models import Review


class Restaurant(models.Model):
    user = models.OneToOneField(User, related_name="restaurant", on_delete=models.CASCADE)
    website_link = models.URLField(max_length=200, blank=True)
    facebook_link = models.URLField(max_length=200, blank=True)
    logo = CloudinaryField("image", blank=True, folder="media/restaurants/")
    description = models.TextField(blank=True)
    open_hour = models.TimeField(auto_now=False, auto_now_add=False)
    close_hour = models.TimeField(auto_now=False, auto_now_add=False)
    is_available = models.BooleanField(default=True)
    reviews = GenericRelation(
        Review,
        related_query_name="restaurant",
        content_type_field="content_type",
        object_id_field="object_id",
    )
    favourites = GenericRelation(
        Favourite,
        related_query_name="food",
        content_type_field="content_type",
        object_id_field="object_id",
    )
    location = ArrayField(models.CharField(max_length=500, blank=True), size=3)
    has_logged_once = models.BooleanField(default=False)
    created = models.TimeField(auto_now_add=True)
    updated = models.TimeField(auto_now=True)

    # Managers
    objects = models.Manager()
    available = AvailabilityManager()
    tags = TaggableManager()

    class Meta:
        ordering = ("-is_available",)

    @property
    def average_ratings(self):
        avg_ratings = self.reviews.aggregate(Avg("ratings")).get("ratings__avg", 0)
        if avg_ratings == None: avg_ratings = 0
        return avg_ratings

    @property
    def ratings_count(self):
        ratings_cnt = self.reviews.aggregate(Count("ratings")).get("ratings__count", 0)
        if ratings_cnt == None: ratings_cnt = 0
        return ratings_cnt

    @property
    def open_status(self):
        open_hour = self.open_hour
        close_hour = self.close_hour
        IST = pytz.timezone("Asia/Kathmandu")
        current_time = datetime.datetime.now(IST).time()
        return current_time >= open_hour and current_time <= close_hour

    def clean(self):
        if self.open_hour > self.close_hour:
            raise ValidationError('Opening hour should be greater than closing hours.')
        return super().clean()

    def customer_favourite_status(self, id):
        try:
            customer = Customer.objects.get(id=id)
            item = self.favourites.filter(customer=customer)
            if item:
                return True
            return False
        except ObjectDoesNotExist:
            return False

    def distance(self, lat, lng):
        from geopy.distance import geodesic
        location = self.location
        return geodesic((location[0], location[1]), (lat, lng)).km

    @property
    def has_location(self):
        return all(self.location)

    def __str__(self):
        representation =  f"{self.user.full_name} for user {self.user.username}" if self.user.full_name else self.user.username
        return representation


@receiver(post_delete, sender=Restaurant)
def post_delete_callback(sender, instance, **kwargs):
    user = User.objects.get(id=instance.user.id)
    user.delete()

backend/restaurants/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.core.exceptions import ValidationError

from restaurants.models import Restaurant
from accounts.models import User


class RestaurantRegistrationForm(forms.Form):
    full_name = forms.CharField(max_length=250, required=True)
    phone_number = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(required=False)
    open_hour = forms.TimeField(required=True)
    close_hour = forms.TimeField(required=True)

    def clean_close_hour(self):
        ''' Validate closing time to be greater than opening time. '''
        open_hour = self.cleaned_data.get('open_hour')
        close_hour = self.cleaned_data.get('close_hour')

        if open_hour >= close_hour:
            raise forms.ValidationError('Closing hour should be greater than opening hour!')

        return close_hour


class RestaurantNameUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["full_name"]

    def clean(self, *args, **kwargs):
        data = super().clean(*args, **kwargs)
        if not data.get("full_name"):
            raise ValidationError("Name cannot be empty!")
        return data


class RestaurantAccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = [
            "description", "open_hour", "close_hour",
            "website_link", "facebook_link", "is_available",
            "logo", "tags",
        ]


class CustomChangePasswordForm(PasswordChangeForm):
    pass

backend/foods/views.py
from django.core.exceptions import ObjectDoesNotExist

from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView
)
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from rest_framework.authentication import TokenAuthentication, SessionAuthentication
from rest_framework.response import Response
from rest_framework.status import HTTP_403_FORBIDDEN, HTTP_404_NOT_FOUND

from api import custompermissions, customauthentication

from foods.models import Food, FoodTemplate
from foods.serializers import FoodSerializer, FoodTemplateSerializer
from foods.custompermissions import IsCurrentRestaurantOwnerOrReadOnly


class FoodList(ListCreateAPIView):
    serializer_class = FoodSerializer
    permission_classes = [
        IsAuthenticatedOrReadOnly,
        custompermissions.IsCurrentUserRestaurant,
        IsCurrentRestaurantOwnerOrReadOnly
    ]
    authentication_classes = [
        TokenAuthentication,
        customauthentication.CsrfExemptSessionAuthentication
    ]

    def perform_create(self, serializer):
        serializer.save(restaurant=self.request.user.restaurant)
        return super().perform_create(serializer)
    
    def get_queryset(self):
        queryset = Food.objects.all()
        latitude = self.request.query_params.get('lat', None)
        longitude = self.request.query_params.get('lng', None)
        top_rated = self.request.query_params.get('top_rated', None)
        favorite = self.request.query_params.get('favorite', None)
        veg = self.request.query_params.get('veg', None)
        offers = self.request.query_params.get('offers', None)
        query = self.request.query_params.get('query', None)

        if latitude and longitude:
            # for every queryset, calculate distance from the given lat and lng and filter if distance is less than 4km
            for q in queryset:
                if q.restaurant.distance(latitude, longitude) > 10:
                    queryset = queryset.exclude(id=q.id)
        if top_rated:
            for q in queryset:
                if q.average_ratings <= 3:
                    queryset = queryset.exclude(id=q.id)
        if favorite:
            if self.request.user.is_authenticated and self.request.user.is_customer:
                for q in queryset:
                    if q.customer_favourite_status(id=self.request.user.customer.id) == False:
                        queryset = queryset.exclude(id=q.id)
        if veg:
            for q in queryset:
                if q.is_veg == False:
                    queryset = queryset.exclude(id=q.id)
        if offers:
            for q in queryset:
                if not q.discount_percent:
                    queryset = queryset.exclude(id=q.id)
            queryset = queryset.order_by('-discount_percent')
        
        if query:
            queryset = queryset.filter(tags__name__in=[query,])
        return queryset


class FoodDetails(RetrieveUpdateDestroyAPIView):
    queryset = Food.objects.all()
    serializer_class = FoodSerializer
    permission_classes = [
        IsAuthenticatedOrReadOnly,
        custompermissions.IsCurrentUserRestaurant,
        IsCurrentRestaurantOwnerOrReadOnly
    ]
    authentication_classes = [
        TokenAuthentication,
        customauthentication.CsrfExemptSessionAuthentication
    ]


class FoodTemplateList(ListAPIView):
    queryset = FoodTemplate.objects.all()
    serializer_class = FoodTemplateSerializer
    permission_classes = [IsAuthenticated,
                          custompermissions.AllowOnlyRestaurant]
    authentication_classes = [
        TokenAuthentication,
        customauthentication.CsrfExemptSessionAuthentication
    ]


class FoodTemplateDetailsView(RetrieveAPIView):
    queryset = FoodTemplate.objects.all()
    serializer_class = FoodTemplateSerializer
    permission_classes = [IsAuthenticated,
                          custompermissions.AllowOnlyRestaurant]
    authentication_classes = [
        TokenAuthentication,
        customauthentication.CsrfExemptSessionAuthentication
    ]

backend/restaurants/templates/restaurants/base.html
{% extends "accounts/base.html" %}

{% load static %}

{% block extrastyle %}
    .navbar-brand {
        font-style: normal;
        font-weight: 700;
        font-size: 30px;
        line-height: 54px;
    }

    h3 {
        font-style: normal;
        font-weight: 700;
        font-size: 28px;
        line-height: 54px;
    }
    {% block restaurant_extrastyle %}{% endblock %}
{% endblock %}

{% block content %}
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'restaurants:restaurant_home' %}">
                <img src="{{ user.restaurant.logo.url }}"
                    class="rounded"
                    alt="{{ user.full_name }} logo"
                    width=100
                    height=100
                />
                <span class="mx-3">
                    {{ user.full_name }}
                </span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav d-flex align-items-center">
                    <a href="{% url 'restaurants:food_list' %}" class="nav-link text-primary">
                        My Foods
                    </a>
                    <a href="{% url 'restaurants:food_create' %}" class="nav-link text-primary">
                        Add Food
                    </a>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle btn my-md-0 ms-md-3" href="#" id="navbarDropdown"
                        role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa-solid fa-gear fa-2x"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="navbarDropdown">
                            <li>
                                <a href="{% url 'restaurants:account_settings' %}" class="dropdown-item">
                                    <i class="fa-solid fa-user-gear"></i> Account Settings
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'restaurants:get_location' %}" class="dropdown-item">
                                    <i class="fa-solid fa-location-dot"></i> Edit Location
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'restaurants:change_password' %}" class="dropdown-item">
                                    <i class="fa-solid fa-lock"></i> Change Password
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a href="{% url 'accounts:restaurant_logout' %}?next=/" class="dropdown-item">
                                    <i class="fa-solid fa-arrow-right-from-bracket"></i> Logout
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="container">
        {% block restaurant_content %}{% endblock restaurant_content %}
    </div>
</div>
{% endblock content %}

backend/restaurants/templates/restaurants/change_password.html
{% extends "restaurants/base.html" %}

{% load crispy_forms_tags %}

{% block restaurant_content %}
<div class="text-start">
    <h3>Change Password</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group my-3">
            {{ form|crispy }}
        </fieldset>
        <div class="form-group my-2">
            <button class="btn btn-primary" type="submit">Change Password</button>
            <a href="{% url 'restaurants:restaurant_home' %}" class="btn btn-secondary">
                Cancel
            </a>
        </div>
    </form>
</div>
{% endblock restaurant_content %}

backend/restaurants/templates/restaurants/food_detail.html
{% extends "restaurants/base.html" %}

{% load static %}
{% load restaurants_tags %}

{% block restaurant_content %}
<div class="text-start">
    <h3>Food Details: {{ food.name }}</h3>
    <div class="row my-2">
        <div class="col-md-5 d-flex flex-column align-items-center">
            <div class="row">
                <img src="{% if food.image.url %}{{ food.image.url }}{% else %}{% static 'restaurants/img/noimage.png' %}{% endif %}" alt="{{ food.name }}" width=200 height=200 />
            </div>
            <span class="my-2">
                <a href="{% url 'restaurants:food_update' food.id %}">
                    <i class="fa-solid fa-pen-to-square text-primary"></i>
                </a>
                &nbsp;
                <a href="{% url 'restaurants:food_delete' food.id %}">
                    <i class="fa-solid fa-trash text-danger"></i>
                </a>
            </span>
        </div>
        <div class="col-md-7">
            {% if food.tags.all %}
                <div class="row mb-2">
                    <div class="col-md-12">
                        {% for tag in food.tags.all %}
                            <span class="badge rounded-pill bg-primary">
                                {{ tag }}
                            </span>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-5"><b>Description</b></div>
                <div class="col-md-7">{{ food.description }}</div>
            </div>
            <div class="row">
                <div class="col-md-5"><b>Price</b></div>
                <div class="col-md-7">
                    Rs.
                    {% if food.discount_percent > 0 %}
                        <span class="text-muted"><del>{{ food.price }}</del></span> {{ food.selling_price }}
                    {% else %}
                        {{ food.price }}
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-5"><b>Vegetarian</b></div>
                <div class="col-md-7">{{ food.is_veg }}</div>
            </div>
            <div class="reviews my-5">
                <h4>Reviews <small>({{ food.reviews.all.count }})</small></h4>
                <div class="reviews-list my-2">
                    {% if food.reviews.all %}
                        {% for review in food.reviews.all %}
                            <div class="d-flex align-items-center border border-secondary rounded p-2 mb-2">
                                <img src="{% if review.customer.profile_picture %}{{ review.customer.profile_picture }}{% else %}{% static 'restaurants/img/noimage.png' %}{% endif %}" class="rounded-circle" alt="{{ review.customer.user.full_name }}" width=75 height=75>
                                <div class="p-2">
                                  <div>
                                    <span class="card-title"><b>{{ review.customer.user.full_name }}</b> </span>
                                    <span>
                                      {% for i in review.ratings|times %}
                                          <i class="fa-solid fa-star text-warning"></i>
                                      {% endfor %}
                                    </span>
                                  </div>
                                  <p class="card-text">{{ review.comment }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p class="text-muted">Sorry, no review to show!</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock restaurant_content %}

backend/restaurants/templates/restaurants/food_form.html
{% extends "restaurants/base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block restaurant_content %}
<div class="container text-start">
    <div class="row">
       <div class="col-md-8">
           <h3>Add/Edit Food</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="my-2">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a href="{% url 'restaurants:food_list' %}" class="btn btn-secondary">
                        Cancel
                    </a>
                </div>
            </form>
        </div>
        {% if page == "create" %}
        <div class="col-md-4 border border-rounded py-3">
            <h4>Templates</h4>
            {% if templates %}
            <p class="text-muted">Some templates to help you with quick addition of food to your dashboard!</p>
            {% for template in templates %}
                <div class="card m-2" style="width: 18rem;">
                    <a href="{% url 'restaurants:food_create_from_template' template.id %}">
                        <img class="card-img-top" src="{% if template.image.url %}{{ template.image.url }}{% else %}{% static 'restaurants/img/noimage.png' %}{% endif %}" alt="{{ template.name }}" width=100 />
                    </a>
                    <div class="card-body">
                        <a href="{% url 'restaurants:food_create_from_template' template.id %}">
                            <h5 class="card-title">{{ template.name }}</h5>
                        </a>
                        <p class="card-text">Rs. {{ template.price }}</p>
                        <p class="card-text">{{ template.description  }}</p>
                    </div>
                </div>
            {% endfor %}
            {% else %}
                <p class="text-muted">Sorry, no template for food available at the moment!</p>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock restaurant_content %}

backend/restaurants/templates/restaurants/food_list.html
{% extends "restaurants/base.html" %}

{% load static %}

{% block restaurant_content %}
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>

<div class="text-start">
    <div class="d-flex justify-content-between align-items-center">
        <h3>Food List</h3>
        <a href="{% url 'restaurants:food_create' %}" class="btn btn-primary">
            <i class="fa-solid fa-add"></i> Add food
        </a>
    </div>

    <div class="my-3">
        {% if foods %}
            <div class="row">
                {% for food in foods %}
                    <div class="card col-md-3 m-2" style="width: 18rem;">
                        <a href="{% url 'restaurants:food_detail' food.id %}">
                            <img class="card-img-top" src="{% if food.image.url %}{{ food.image.url }}{% else %}{% static 'restaurants/img/noimage.png' %}{% endif %}" alt="{{ food.name }}" width=100 />
                        </a>
                      <div class="card-body">
                        <a href="{% url 'restaurants:food_detail' food.id %}">
                            <h5 class="card-title">{{ food.name }}</h5>
                        </a>
                        <p class="card-text">
                            {% for tag in food.tags.all %}
                                <span class="badge rounded-pill bg-primary">
                                    {{ tag }}
                                </span>
                            {% endfor %}
                        </p>
                        <p class="card-text">
                            Rs.
                            {% if food.discount_percent > 0 %}
                                <span class="text-muted"><del>{{ food.price }}</del></span> {{ food.selling_price }}
                            {% else %}
                                {{ food.price }}
                            {% endif %}
                        </p>
                        <p class="card-text">
                            {% if food.is_veg %}
                                <img src="{% static 'restaurants/img/veg.svg' %}" width=20>
                                <span class="text-muted"> Vegetarian</span>
                            {% else %}
                                <img src="{% static 'restaurants/img/non-veg.svg' %}" width=20>
                                <span class="text-muted"> Non-vegetarian</span>
                            {% endif %}
                        </p>

                        <p class="card-text">{{ food.description  }}</p>
                        <span>
                            <a href="{% url 'restaurants:food_update' food.id %}">
                                <i class="fa-solid fa-pen-to-square text-primary"></i>
                            </a>
                            &nbsp;
                            <a href="{% url 'restaurants:food_delete' food.id %}">
                                <i class="fa-solid fa-trash text-danger"></i>
                            </a>
                        </span>
                      </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            No food added!
            <a href="{% url 'restaurants:food_create' %}">Add Food</a>
        {% endif %}
    </div>
</div>
{% endblock restaurant_content %}